blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.posts, name="blog"),
    path("create", views.create_post, name="create"),
    path("<slug:slug>", views.post, name="post"),
]

mysite/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from . import views

urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("about/", views.about),
    path("", include("blog.urls")),
    path("users/", include("users.urls")),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.signin, name="login"),
    path("logout/", views.sign_out, name="logout"),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True, default=None)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default="fallback.jfif", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __repr__(self):
        return f"<Post: {self.title}>"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

users/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django.forms import ModelForm

from .models import Post


class CreatePost(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "slug", "body", "banner"]

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import CreatePost
from .models import Post


def posts(request):
    posts_list = Post.objects.all().order_by("date")
    return render(request, "blog/posts.html", {"posts": posts_list})


def post(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, "blog/post.html", {"post": post})


@login_required(login_url="/users/login")
def create_post(request):
    if request.method == "POST":
        form = CreatePost(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect("blog:blog")
        return render(request, "blog/create_post.html", {"form": form})

    form = CreatePost()

    return render(request, "blog/create_post.html", {"form": form})

mysite/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("blog:blog")
        return render(request, "users/register.html", {"form": form})

    form = UserCreationForm()
    return render(request, "users/register.html", {"form": form})


def signin(request):
    full_path = request.get_full_path()
    next = request.GET.get("next", "/")

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect(next)
        return render(
            request, "users/login.html", {"form": form, "full_path": full_path}
        )

    form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form, "full_path": full_path})


def sign_out(request):
    logout(request)
    return redirect("users:login")

blog/templates/blog/create_post.html
{% extends 'layout.html' %}

{% block title %} Create Post {% endblock %}

{% block content %}
<main class="container flex flex-col items-center min-h-[calc(100vh-4rem)] py-6 border-gray-50">
    <h1 class="text-3xl font-bold my-4">
        Create Post
    </h1>
    <form
        class="space-y-4"
        action="{% url 'blog:create' %}"
        method="POST"
        enctype="multipart/form-data"
    >
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
            Create Post
        </button>

    </form>
</main>
{% endblock %}

blog/templates/blog/post.html
{% extends 'layout.html' %}

<!--title-->
{% block title %} {{ post.title }} {% endblock %}

<!--content-->
{% block content %}
<main class="container min-h-[calc(100vh-4rem)] py-6">
    <img
        src="{{ post.banner.url }}"
        alt="{{ post.title }}"
        class="bg-muted my-8 h-auto max-h-[405px] w-full max-w-[720px] rounded-md border transition-colors"
    />
    <h1 class="text-3xl font-bold">{{ post.title }}</h1>
    <p class="text-gray-500">{{ post.body }}</p>
    <h6 class="mb-5 text-sm font-light">{{ post.date }}</h6>
</main>
{% endblock %}

blog/templates/blog/posts.html
{% extends 'layout.html' %}

<!--Title-->

{% block title %} Home {% endblock %}

<!--Content-->

{% block content %}
<main class="container min-h-[calc(100vh-4rem)] py-6">
    <pre>
        {{ user.role }}
    </pre>
    <hgroup class="max-w-sm flex-1 space-y-2 text-pretty">
        <h1 class="inline-block text-3xl font-bold tracking-tight lg:text-4xl">Blog</h1>
        <p class="text-pretty font-medium tracking-tight text-gray-400">
            Sharing Thoughts, Projects, and a Little Bit of Everything in Between
        </p>
    </hgroup>

    {% if posts %}
    <div class="mt-10">
        {% for post in posts %}
        <article
            class="w-[300px] rounded-2xl border border-gray-600 bg-white p-5 shadow-sm"
        >
            <h3 class="font-bold text-blue-500">{{ post.title }}</h3>
            <p class="">{{ post.body }}</p>
            <h6 class="mb-5 text-sm font-light">{{ post.date }}</h6>
            <hr class="my-5" />
            <p class="text-gray-500">
                By <span class="font-bold">{{ post.author }}</span>
            </p>
            <hr class="my-5" />
            {% if user.is_authenticated and user == post.author %}
            <form action="" method="DELETE">
                <button class=" flex gap-2 text-white items-center justify-center bg-red-600 py-1 px-2 rounded-lg hover:bg-red-700">
                    <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M10 12V17" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M14 12V17" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M4 7H20" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M6 10V18C6 19.6569 7.34315 21 9 21H15C16.6569 21 18 19.6569 18 18V10" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M9 5C9 3.89543 9.89543 3 11 3H13C14.1046 3 15 3.89543 15 5V7H9V5Z" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
                    Delete
                </button>
            </form>
            {% endif %}
            <a
                href="{% url 'blog:post' slug=post.slug %}"
                class="rounded-lg bg-blue-400 px-4 py-2 text-center text-white hover:bg-blue-500"
                >Read more &rarr;</a
            >
        </article>
        {% endfor %}
    </div>

    {% endif %}

    <div class="">{% for post in posts %} {% endfor %}</div>
</main>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

<!--Title-->

{% block title %} Blog {% endblock %}

<!--Content-->

{% block content %}
<main class="flex min-h-[calc(100vh-4rem)] flex-col items-center justify-center">
    <h1 class="text-3xl font-black">About</h1>
</main>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

<!--Title-->

{% block title %} Home {% endblock %}

<!--Content-->

{% block content %}
<main class="flex min-h-[calc(100vh-4rem)] flex-col items-center justify-center">
    <h1 class="text-3xl font-black">
        {% if user.is_authenticated %}
          Hello, <span class="{% if user.is_superuser %}text-red-600{% endif %}">{{ user.username }}</span>.
        {% else %}
            Hello, there.
        {% endif %}
    </h1>
    <p>Welcome to my website.</p>
</main>
{% endblock %}

templates/layout.html
<!doctype html>
{% load static %}
<html lang="en" class="scroll-smooth focus:scroll-auto">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
            rel="stylesheet"
        />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <link rel="stylesheet" href="{% static 'css/tw.css' %}" />
        <title>{% block title %} Django App {% endblock %}</title>
    </head>
    <body class="font-serif">
        {% block navbar %}
            {% include "navbar.html" %}
        {% endblock %}

        {% block content %}{% endblock %}
    </body>
</html>

templates/navbar.html
<header class="container bg-white sticky top-0 flex h-16 items-center dark:bg-gray-900">
    <nav class="flex-1 border-gray-200 ">
    <div
        class="mx-auto flex max-w-screen-xl flex-wrap items-center justify-between dark:bg-gray-900"
    >
        <a href="/" class="flex items-center">
            <svg
                viewBox="0 0 250 250"
                xmlns="http://www.w3.org/2000/svg"
                stroke="#000"
                stroke-width="0.00256"
                class="{% if user.is_superuser %}fill-red-600{% endif %} size-8"
            >
                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                <g
                    id="SVGRepo_tracerCarrier"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke="#CCCCCC"
                    stroke-width="3.072"
                ></g>
                <g id="SVGRepo_iconCarrier">
                    <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M50.455 102.855c0 25.177 39.647 105.629 77.265 105.629h.001c37.619 0 77.397-76.894 77.397-108.531 0-20.003-18.606-52.373-77.62-52.373-59.013 0-77.043 35.758-77.043 55.275zm50.039 5.634C86.402 93.277 77.656 77.857 77.656 77.857s14.41-7.175 23.824-9.091c.802-.163 1.62-.338 2.458-.516 8.997-1.916 20.189-4.298 36.328 1.496 33.579 12.056 47.896 34.606 47.896 34.606s-21.609-17.401-45.404-20.895c-13.707-2.013-39.203 6.152-39.203 6.152s8.862 9.38 16.075 23.114c1.137 2.165 2.245 4.147 3.306 6.045 5.668 10.137 9.974 17.838 9.974 37.93 0 14.659-11.08 36.443-11.08 36.443s6.223-28.383 1.204-50.825c-3.627-16.223-6.425-18.719-13.02-24.603-2.528-2.255-5.615-5.008-9.52-9.224z"
                    ></path>
                </g>
            </svg>
            <span
                class="whitespace-nowrap {% if user.is_superuser %}text-red-600{% endif %} font-mono text-xl font-semibold dark:text-white"
                >
                Django App
                {% if user.is_superuser %}
                    <sup class="text-red-600 ">⭐</sup>
                {% endif %}
            </span>
        </a>
        <button
            data-collapse-toggle="navbar-default"
            type="button"
            class="inline-flex h-10 w-10 items-center justify-center rounded-lg p-2 text-sm text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 md:hidden dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
            aria-controls="navbar-default"
            aria-expanded="false"
        >
            <span class="sr-only">Open main menu</span>
            <svg
                class="h-5 w-5"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 17 14"
            >
                <path
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M1 1h15M1 7h15M1 13h15"
                />
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
            <ul
                class="mt-4 flex flex-col rounded-lg border border-gray-100 bg-gray-50 p-4 font-medium md:mt-0 md:flex-row md:space-x-8 md:border-0 md:bg-white md:p-0 rtl:space-x-reverse dark:border-gray-700 dark:bg-gray-800 md:dark:bg-gray-900"
            >
                <li>
                    <a
                        href="/about"
                        class="block rounded px-3 py-2 text-gray-900 hover:bg-gray-100 md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
                        >About</a
                    >
                </li>
                <li>
                    <a
                        href="{% url 'blog:blog' %}"
                        class="block rounded px-3 py-2 text-gray-900 hover:bg-gray-100 md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
                    >
                        Blog
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li>
                        <a
                            href="{% url 'users:register' %}"
                            class="block rounded px-3 py-2 text-gray-900 hover:bg-gray-100 md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
                            >Register</a
                        >
                    </li>
                    <li>
                        <a
                            href="{% url 'users:login' %}"
                            class="block rounded px-3 py-2 text-gray-900 hover:bg-gray-100 md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
                            >Login</a
                        >
                    </li>
                {% else %}
                    <li>
                        <a
                            href="{% url 'blog:create' %}"
                            class="block rounded px-3 py-2 text-gray-900 hover:bg-gray-100 md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
                        >
                            Create post
                        </a>
                    </li>
                    <li>
                        <a
                            href="{% url 'users:logout' %}"
                            class="block rounded px-3 py-2 text-gray-900 hover:bg-gray-100 md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
                            >Logout</a
                        >
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
</header>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}Login{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}
<main
    class="container flex min-h-[calc(100vh-4rem)] flex-col items-center justify-center bg-gray-50 py-6"
>
      <section class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
          <a
            href="/"
            class="mb-6 flex items-center text-2xl font-semibold text-gray-900 dark:text-white"
        >
            <svg
                fill="#000"
                width="35px"
                height="35px"
                viewBox="0 0 250 250"
                xmlns="http://www.w3.org/2000/svg"
                stroke="#000"
                stroke-width="0.00256"
            >
                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                <g
                    id="SVGRepo_tracerCarrier"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke="#CCCCCC"
                    stroke-width="3.072"
                ></g>
                <g id="SVGRepo_iconCarrier">
                    <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M50.455 102.855c0 25.177 39.647 105.629 77.265 105.629h.001c37.619 0 77.397-76.894 77.397-108.531 0-20.003-18.606-52.373-77.62-52.373-59.013 0-77.043 35.758-77.043 55.275zm50.039 5.634C86.402 93.277 77.656 77.857 77.656 77.857s14.41-7.175 23.824-9.091c.802-.163 1.62-.338 2.458-.516 8.997-1.916 20.189-4.298 36.328 1.496 33.579 12.056 47.896 34.606 47.896 34.606s-21.609-17.401-45.404-20.895c-13.707-2.013-39.203 6.152-39.203 6.152s8.862 9.38 16.075 23.114c1.137 2.165 2.245 4.147 3.306 6.045 5.668 10.137 9.974 17.838 9.974 37.93 0 14.659-11.08 36.443-11.08 36.443s6.223-28.383 1.204-50.825c-3.627-16.223-6.425-18.719-13.02-24.603-2.528-2.255-5.615-5.008-9.52-9.224z"
                    ></path>
                </g>
            </svg>
            Flowbite
        </a>
          <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
              <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                  <hgroup>
                    <h1
                        class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white"
                    >
                        Sign to your account
                    </h1>
                    <p class="text-gray-400 text-sm">
                        to continue to <a href="/" class="underline-offset-4 hover:underline"><strong>Django App</strong></a>
                    </p>
                  </hgroup>
                  <form
                      class="space-y-4 md:space-y-6"
                      action="{{ full_path }}"
                      method="post">
                      {% csrf_token %}
                      {{ form }}
<!--                      <div>-->
<!--                          <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>-->
<!--                          <input type="email" name="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required="">-->
<!--                      </div>-->
<!--                      <div>-->
<!--                          <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>-->
<!--                          <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">-->
<!--                      </div>-->
<!--                      <div class="flex items-center justify-between">-->
<!--                          <div class="flex items-start">-->
<!--                              <div class="flex items-center h-5">-->
<!--                                <input id="remember" aria-describedby="remember" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">-->
<!--                              </div>-->
<!--                              <div class="ml-3 text-sm">-->
<!--                                <label for="remember" class="text-gray-500 dark:text-gray-300">Remember me</label>-->
<!--                              </div>-->
<!--                          </div>-->
<!--                          <a href="#" class="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500">Forgot password?</a>-->
<!--                      </div>-->
                      <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Sign in</button>
                      <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                          Don’t have an account yet? <a href="{% url 'users:register' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign up &rarr;</a>
                      </p>
                  </form>
              </div>
          </div>
  </section>
</main>
{% endblock %}